name: setup-and-test
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: npm
      - run: make setup
      - run: make test
      - run: make lint
      - uses: actions/checkout@master
      - name: Run Snyk to chek ulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: $ {{ secrets.SNYK }}
